language: generic
sudo: false
go:
- 1.7.x
cache:
  directories:
  - $HOME/.local/bin
  - $HOME/.stack
os:
- linux
- osx
before_install:
- sh tools/install-stack.sh
install:
- go get -u github.com/tcnksm/ghr
script:
- stack setup
- stack build --ghc-options -O2 --pedantic
after_success:
- sh tools/attach-binary.sh
